name: ci

on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: checkout
        uses: actions/checkout@v2
      - name: cache
        uses: actions/cache@v2.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v2.3

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: go build -o syosyo

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: go test -v
