name: upload

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "csv/**"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make syosyo
      - run: make generate-jisyo
      - run: make ci-upload
        env:
          AWS_DEFAULT_REGION: fake
          AWS_EC2_METADATA_DISABLED: true
          AWS_ENDPOINT_URL: https://object-storage1.chasoba.net
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
